/* Piyasa Kası — Veri Dosyası 4: 2026 senaryoları (web araştırmasıyla derlenen gerçek olaylar) */

window.PK_D = [
S("Nvidia","Bilanço","bilanco","25 Şubat 2026 · Bilanço kapanıştan sonra","Nvidia bilançosu: rekor kesin, soru artık 'yeter mi?'",["Gelirin 68 milyar dolarla rekor kırması bekleniyor (+%70 üstü büyüme).","Ama tartışma değişti: 'Yapay zekâ harcamaları sürdürülebilir mi?'","Hisse iki yıldır ralli yapıyor; çıta tarihin en yükseğinde."],168,190,-6,"Rakamlar beklentiyi ezdi (68,1 milyar $, guidance 78 milyar $) — hisse yine de ertesi gün %5,5, sonraki gün %4 daha düştü. Tartışma rakamlardan sürdürülebilirliğe kayınca, mükemmel sonuç bile yetmez.","cita","1 gün"),
S("Brent Petrol","Arz Şoku","emtia","Mart 2026 başı · Savaşın ilk günleri","İran savaşı: Hürmüz Boğazı fiilen kapandı, petrol 85$",["Savaş başladı; petrol 73$'tan 85$'a sıçradı bile.","'Her jeopolitik spike söner' diyenler short arıyor (2022 ve 2025 örnekleri taze).","Ama bu kez fark var: Hürmüz kapalı — küresel arzın ~%20'si fiilen kesildi."],72,85,40,"Petrol 120$'ı aştı (+%40): IEA 'tarihin en büyük arz kesintisi' dedi. Kritik ayrım: arz FİİLEN kesilirse spike söner kuralı geçersizdir — 2025'te doğru olan short, 2026'da felaketti.","arz","1 ay"),
S("Altın (ons)","Panik Testi","zirve","Mart 2026 başı · Savaş haftası","Savaş patladı, altın 5.400$ zirvesinde: güvenli liman alınır mı?",["Altın aylardır rallide; savaş haberiyle 5.400$ tepe yaptı.","'Savaş = altın alınır' refleksi her yerde.","Ama marj çağrıları başladı; fonlar nakit için kârdaki varlıkları satıyor."],4900,5400,-25,"Altın savaşa RAĞMEN %25 düşüp 4.000$'a geriledi — güvenli liman rolü sorgulandı. Ders üçüncü kez: gerçek likidite panikinde her şey satılır, kâr edilen en önce.","carry","1-3 ay"),
S("Nasdaq 100","Düzeltme Dibi","zirve","Mart 2026 sonu · 5. düşüş haftası","Nasdaq resmi düzeltmede: üst üste 5 haftalık düşüş",["S&P, 2022'den beri en uzun haftalık düşüş serisinde.","Sebepler üst üste: İran savaşı, petrol şoku, Çin'in ABD'ye ticaret soruşturması.","Küçük hisseler (Russell 2000) çoktan düzeltmede; karamsarlık zirvede."],24000,21600,15,"Mart dibinden Nasdaq %31 ralli yaptı (ilk 2 ayda +%15): yarı iletken endeksi yıl ortasında +%80'e ulaştı. Dipler yine en kötü manşetlerin ortasında oluştu.","panik","1-3 ay"),
S("Nasdaq 100","Makro Veri","makro","5 Haziran 2026 · İstihdam verisi sabahı","İstihdam beklentinin İKİ KATI geldi: güçlü ekonomi, güçlü piyasa?",["172 bin istihdam (beklenti ~80 bin) — ekonomi çok güçlü.","Ama 2026 rejimi farklı: enflasyon yeniden yükselişte, FED'in faiz ARTIRMASI konuşuluyor.","Nasdaq, Mart dibinden %31 ralli yapmış durumda; kâr realizasyonu için bahane aranıyor."],22800,23800,-4.2,"Nasdaq -%4,2 (yılın en kötü günü): güçlü veri = faiz artırım ihtimali = satış. 1,8 trilyon dolar silindi; Micron -%10, Sandisk -%11. 'İyi haber kötü haberdir' rejimi geri döndü.","rejim","1 gün"),
S("SpaceX","Halka Arz","ipo","12 Haziran 2026 · İlk işlem günü kapanışı","SpaceX: tarihin en büyük halka arzı ilk gün +%19 kapattı",["75 milyar dolar toplandı — tüm zamanların rekoru; değerleme 1,77 trilyon $.","135$'lık arz 150$'dan açıldı, 161$'dan kapandı; gün içinde +%30 görüldü.","'İlk gün pop'u satılır' kuralcıları ile 'bu başka bir şey' diyenler karşı karşıya."],135,161,20,"İlk tam işlem gününde +%20 daha: talep o kadar derindi ki kural yine bozuldu (hacim Facebook 2012'ye yaklaştı). Neslin en büyük hikâyelerinde ilk gün, dağıtım değil keşif günüdür — ama pozisyon yine küçük tutulur.","trend","1 gün"),
S("Nikkei 225","Şok Haber","sok","15 Haziran 2026 · Pazar gecesi anlaşma sonrası","ABD-İran anlaşma çerçevesi açıklandı: Asya nasıl açılır?",["Pazar günü sosyal medyadan duyuruldu: Hürmüz yeniden açılıyor, abluka kalkıyor.","Aylardır süren savaş piyasaların üstünde kâbus gibiydi.","Asya borsaları anlaşma sonrası ilk açılacak piyasalar."],46500,45800,5.5,"Nikkei +%5,5, Kospi +%5,7 fırladı; petrol düştü. Politika/savaş şoku nasıl çökertiyorsa, çözüm haberi de aynı şiddette ralli yaptırır — barış, en güçlü katalizördür.","panik","1 gün"),
S("S&P 500","FED Kararı","fed","17 Haziran 2026 · FOMC kararına 1 saat","FED kararı: 'sabit tutar' fiyatlı — ama nokta grafiği ne diyecek?",["Faizin 3,50-3,75'te sabit kalması kesine yakın fiyatlanmış.","Asıl soru: savaş sonrası petrol şoku enflasyon tahminlerini nasıl etkiledi?","Piyasa hâlâ 'sıradaki hamle indirim' varsayımında."],7150,7220,-1.5,"Faiz sabit kaldı ama nokta grafiği İNDİRİMDEN ARTIRIMA döndü (2026 sonu medyanı 3,8): endeks ~%1 düştü, 2 yıllık tahvil sıçradı. Karar değil, patika konuşur — dot plot sürprizi 2026'nın rejim değişimiydi.","basin","1 gün"),
S("Bitcoin","Ölü Kedi Testi","kripto","Nisan 2026 · Toparlanma denemesi","Bitcoin dipten %13 toparladı: 82k — dönüş mü, ölü kedi mi?",["Ekim zirvesi 126k'dan 72k'ya düşülmüştü; Nisan rallisi 82k'da tıkandı.","ETF'lerden çıkış serisi hâlâ rekor uzunlukta — akış dönmedi.","FED şahinleşiyor; risk iştahı zayıf."],72000,82000,-20,"Ölü kediydi: Haziran'da ikinci bacak geldi (-%14) ve BTC 60.862$ ile yıl dibini gördü — zirveden -%49. Akış (ETF çıkışları) dönmeden 'toparlanıyor' demek için erkendir.","ucuz","1-3 ay"),
S("Bitcoin","Güven Şoku","kripto","2026 ortası · Haber günü","'Asla satmayız' diyen Strategy (Saylor) Bitcoin sattı",["Saylor yıllardır 'asla satmam' yeminiyle sektörün amiral boğasıydı.","Haber: şirket sembolik de olsa satış yaptı.","'Küçük bir satış, önemi yok' diyenler var."],75000,71000,-10,"Sembolik satış, psikolojik barajı yıktı: düşüş derinleşti. En büyük boğa yeminini bozduğunda mesele miktar değil, mesajdır — içerdeki adam kuralı kriptoda da geçerli.","kalabalik","1 hafta")
];
