/* Piyasa Kası — Veri Dosyası 6: NİŞ OLAYLAR (PK_E)
   Az bilinen ama öğretici gerçek piyasa anları: kur tabanı kırılması, short squeeze, muhasebe
   skandalı, sermaye kontrolü, merkez bankası müdahalesi, tarihî balon zirveleri.
   - Başlıklar tools/fetch-data.mjs SCEN ile BİREBİR aynı olmalı (realdata eşleşmesi).
   - ctx = karar anında BİLİNEN bilgi (sonucu ele vermez); story = realdata'daki gerçek getirilerle tutarlı.
   - PK_DETAILS ve PK_LESSONS'a Object.assign ile eklenir (data1/data5'ten sonra yüklenmeli). */

window.PK_E = [
S("Dolar/TL","Kur Krizi","tr","13 Ağustos 2018 · Pazartesi kapanışı","Dolar/TL 7'yi gördü: rahip krizi ve yaptırım pazartesisi",
  ["ABD, rahip Brunson krizi nedeniyle Türk çeliği ve alüminyumuna gümrük vergisini ikiye katladı; TL cuma günü tek günde ~%14 değer kaybetti.",
   "Pazartesi Asya seansında dolar/TL 7,24'ü gördü; gün 6,95 civarında kapanıyor.",
   "TCMB ve BDDK hafta sonundan beri likidite ve swap tedbirleri açıklıyor; 'faiz artırımı şart' baskısı büyüyor."],
  5.55,6.95,-12,"Zirve o pazartesiydi: swap kısıtlamaları ve Katar'ın 15 milyar $'lık yatırım taahhüdüyle dolar/TL bir haftada -%12 geriledi; Eylül'de TCMB faizi 625 baz puan artırınca Kasım'da 5,5'e kadar indi. Kur panikleri, politika tepkisiyle en sert ters dönüşü yaşar.","pol","1 hafta"),
S("EUR/CHF (İsviçre frangı)","Kur Tabanı","sok","15 Ocak 2015 · Sabah","ECB'nin dev QE'si kapıda: İsviçre MB 1,20 tabanını ne kadar savunabilir?",
  ["İsviçre MB (SNB), 2011'den beri EUR/CHF'de 1,20 tabanını sınırsız döviz alımıyla koruyor; kur aylardır 1,20'ye yapışık.",
   "Avrupa Merkez Bankası'nın 22 Ocak'ta dev tahvil alımı (QE) açıklaması bekleniyor — euro zayıfladıkça SNB'nin savunma maliyeti katlanıyor.",
   "SNB Başkan Yardımcısı 3 gün önce 'taban para politikamızın temel taşı olmalı' dedi; piyasa tabanı 'risksiz' görüyor."],
  1.2008,1.2008,-17,"Aynı sabah SNB tabanı sürpriz biçimde kaldırdı: EUR/CHF dakikalar içinde 0,85'i gördü, günü ~-%17 kapadı. Tabana güvenen kaldıraçlı pozisyonlar silindi, bazı döviz aracı kurumları iflas etti. Fiyatı sabit tutan taahhüt değil, taahhüdü sürdürme gücüdür.","taahhut","1 gün"),
S("UBS","Bankacılık Krizi","sok","20 Mart 2023 · Pazartesi kapanışı (NYSE)","UBS, Credit Suisse'i hafta sonu zorla devraldı: ilk gün kapanışı",
  ["İsviçre hükümetinin baskısıyla UBS, 167 yıllık rakibi Credit Suisse'i sadece ~3 milyar CHF'ye (hisse takasıyla) aldı; devlet 9 milyar CHF'lik zarar garantisi verdi.",
   "CS'nin ~16 milyar CHF'lik AT1 tahvilleri sıfırlandı — hisseden önce tahvilin silinmesi piyasayı şoke etti.",
   "UBS hissesi sabah sert düşüşle açıldı, gün sonunda yeşile döndü (NYSE +%3,3). 'UBS çöplüğü yuttu' mu, 'yılın pazarlığı' mı?"],
  18.2,18.8,12,"Piyasa ikinci düşünceye geçti: ertesi gün +%12, 6 ayda +%39, 1 yılda +%66. Zorunlu birleşmede alıcı, varlıkları devlet garantisiyle çok ucuza alır — ilk korku fiyatlandıktan sonra krizin kazananı ortaya çıkar.","kazanan","1 gün"),
S("Kodak","Hype Rallisi","meme","29 Temmuz 2020 · Kapanış","Kodak iki günde +%1.150: devletten ilaç üretimi kredisi",
  ["ABD hükümeti, fotoğraf devi Kodak'a ilaç hammaddesi üretimi için 765 milyon $'lık kredi verileceğini duyurdu — pandemi 'yerli üretim' hamlesi.",
   "Hisse iki günde 2,6$'dan 33$'a çıktı (gün içi 60$); bireysel yatırımcı uygulamalarında en çok alınan hisse.",
   "Kodak'ın ilaç üretiminde deneyimi yok; kredi imzalanmış değil, şimdilik bir 'niyet mektubu'."],
  2.62,33.2,-55,"Hype bir haftada söndü: -%55. CEO'ya duyurudan bir gün önce hisse opsiyonu verildiği ortaya çıktı; devlet 7 Ağustos'ta krediyi 'usulsüzlük iddiaları' nedeniyle askıya aldı, SEC inceleme başlattı. Bir ayda -%82.","niyet","1 hafta"),
S("Carnival (CCL)","Aşı Şoku","sok","9 Kasım 2020 · Açılış öncesi","Pfizer aşısı %90 etkili: 'kapanan dünyanın' hissesi Carnival",
  ["Pfizer-BioNTech, aşının ara analizde %90'ın üzerinde etkili olduğunu açıkladı — beklentiler %50-70 bandındaydı.",
   "Dünyanın en büyük kruvaziyer şirketi Carnival'ın gemileri aylardır limanda; hisse pandemi öncesinden ~-%75.",
   "Vadelilerde pandemi kazananları (evden çalışma, evde spor) sert düşüyor; 'yeniden açılış' hisseleri uçuyor."],
  13.82,19.25,39,"Carnival tek günde +%39, bir ayda +%70. Pandemi boyunca en çok ezilen 'yeniden açılış' hisseleri, rejimi değiştiren tek veriyle en sert yükselenler oldu.","donus","1 gün"),
S("Bitcoin","Kapitülasyon","kripto","12 Mart 2020 · Gün sonu","Bitcoin tek günde -%39: 4.800$ — kapitülasyon mu, ölüm mü?",
  ["Pandemi paniğinde S&P tek günde -%9,5; Bitcoin 7.900$'dan 4.800$'a çakıldı — yılların en kötü günü.",
   "Kaldıraçlı pozisyonlar zincirleme tasfiye ediliyor; kripto borsalarında emirler yetişemiyor.",
   "'Dijital altın, güvenli liman' tezi çöktü; 'Bitcoin sıfıra gider' manşetleri yayılıyor."],
  7934,4800,16,"Ertesi gün 3.800$'ı test etti ama günü +%16 kapattı; 3 ayda +%106, 1 yılda ~57 bin $. Likidite krizinde her şey satılır — zorunlu satıcılar bittiğinde en sert düşen, en sert döner.","panik","1 gün"),
S("Volkswagen","Short Squeeze","sok","27 Ekim 2008 · Açılış öncesi","Porsche, VW'nin %74'ünü kontrol ettiğini açıkladı: short'lar kıstırıldı",
  ["Porsche pazar akşamı VW adi hisselerinin %42,6'sına sahip olduğunu, opsiyonlarla kontrolünü %74'e çıkardığını açıkladı.",
   "Aşağı Saksonya eyaleti %20,1'e sahip → serbest dolaşımda ~%6 hisse kaldı; oysa açığa satış (short) oranı ~%12.",
   "Hedge fonlar 'VW pahalı' diye short'ta; küresel kriz ortası, otomotiv satışlarının çöktüğünü herkes biliyor."],
  210.85,520,147,"Satın alınacak hisse kalmamıştı: VW pazartesi +%147; salı gün içi 1.005€ ile kısa süreliğine dünyanın en değerli şirketi oldu. Porsche opsiyonların bir kısmını çözünce -%45 geldi, 1 yılda -%45. Dolaşımdaki hisseden fazla short varsa temel analiz geçersizdir — önemli olan kimin almak ZORUNDA olduğudur.","sqz","1 gün"),
S("S&P 500","Tarihî Çöküş","sok","20 Ekim 1987 · Açılış öncesi","Kara Pazartesi'nin ertesi sabahı: S&P tek günde -%20,5",
  ["Dün Dow Jones -%22,6, S&P 500 -%20,5 ile tarihin en kötü gününü yaşadı — 1929'dan bile sert.",
   "Suçlu 'portföy sigortası' denen otomatik satış programları: alıcı bulunamadı, emir sistemleri kilitlendi.",
   "Sabah FED Başkanı Greenspan kısa bir açıklamayla 'likidite kaynağı olmaya hazırız' dedi."],
  282.7,224.84,5,"Salı +%5,3, çarşamba +%9,1; bir yılda +%23. Çöküş mekanik (zorunlu/otomatik satış) ve merkez bankası arkada duruyorsa, en karanlık sabah en iyi alım fırsatıdır.","panik","1 gün"),
S("S&P 500","Sistemik Kriz","sok","15 Eylül 2008 · Açılış öncesi","Lehman Brothers iflas başvurusu yaptı: piyasa nasıl açılır?",
  ["Hafta sonu kurtarma görüşmeleri çöktü: hükümet 'kamu parası yok' dedi, 158 yıllık Lehman iflas başvurusu yaptı.",
   "Aynı hafta sonu Bank of America, Merrill Lynch'i satın aldı; sigorta devi AIG'nin nakit sıkıntısı konuşuluyor.",
   "Mart'ta Bear Stearns kurtarılınca piyasa rahatlamıştı — 'sistem yine kurtarılır' diyenler çok."],
  1251.7,1192.7,-5,"Pazartesi -%4,7. Hafta sonunda açığa satış yasağı ve kurtarma paketi rallisiyle kayıp silindi (1 hafta +%0,3) — ama bu tuzaktı: 1 ayda -%20, 6 ayda -%40. Sistemik krizde ilk tepki rallisi, güvenli çıkış penceresidir; bulaşma zinciri (AIG, para piyasası fonları) haftalar içinde ortaya çıkar.","bulas","1 ay"),
S("Adani Enterprises","Short Raporu","sok","25 Ocak 2023 · Kapanış (Mumbai)","Hindenburg raporu: Adani'de ilk gün sadece -%1,5",
  ["ABD'li short satıcı Hindenburg, Adani Grubu'nu hisse manipülasyonu ve muhasebe hilesiyle suçlayan 100+ sayfalık rapor yayımladı; short pozisyonu açık.",
   "Adani Enterprises ilk gün sadece -%1,5 kapadı; grup raporu 'kötü niyetli ve asılsız' diye reddetti.",
   "Şirket 27 Ocak'ta ~2,5 milyar $'lık ikincil halka arz (FPO) açıyor — 'büyük yatırımcılar destekliyor' deniyor."],
  3442,3388.9,-18,"Sakinlik tuzaktı: sonraki işlem günü -%18,5, bir haftada -%54 (tamamlanan FPO iptal edildi), bir ayda -%61. Ağır iddialı bir raporda ilk günün sakin geçmesi, büyük fonların henüz çıkmadığı anlamına gelir.","gecikme","1 hafta"),
S("GBP/USD (Sterlin)","Politika Hatası","sok","23 Eylül 2022 · Cuma kapanışı","Mini bütçe şoku: sterlin tek günde -%3,6, 'parite' manşetleri",
  ["Yeni Maliye Bakanı Kwarteng, 50 yılın en büyük vergi indirimini finansman planı olmadan açıkladı; İngiliz tahvil faizleri tarihî hızda fırladı.",
   "Sterlin tek günde -%3,6 ile 1,08$'a çöktü; 'sterlin dolara eşitlenir mi (parite)?' manşetleri dönüyor.",
   "İngiltere Merkez Bankası acil adım atmadı; hükümet geri adım atmayacağını söylüyor."],
  1.1264,1.0797,6,"Pazartesi Asya'da sterlin 1,035$ ile tüm zamanların dibini gördü — ama dip oydu. İngiltere MB'nin acil tahvil alımı ve hükümetin U dönüşleriyle bir haftada +%3, üç ayda +%12; Başbakan ~1,5 ay sonra istifa etti. Politika hatası kaynaklı panikte, politika geri adımı en güçlü dönüş katalizörüdür.","pol","1 hafta"),
S("USD/JPY (Dolar/Yen)","Kur Müdahalesi","sok","22 Eylül 2022 · Müdahale günü kapanışı","Japonya 24 yıl sonra ilk kez yen aldı: dolar/yen döner mi?",
  ["Japonya Maliye Bakanlığı 1998'den beri ilk kez piyasaya girip yen aldı; dolar/yen 145,9'dan dakikalar içinde 140,3'e düştü.",
   "Aynı sabah Japonya MB faizi -%0,1'de tuttu; FED ise faizi art arda 75 baz puan artırıyor — faiz farkı açılmaya devam ediyor.",
   "Kur günü 142 civarında kapattı; 'Japonya kararlı, yen dibini gördü' diyenler var."],
  144.3,142.28,4,"Müdahale trendi çeviremedi: faiz farkı açık kaldıkça dolar/yen bir ayda +%4 ile 151,9'a (32 yılın zirvesi) çıktı, ikinci müdahale geldi. Dönüş, ABD enflasyonu yavaşlayıp Japonya MB politikasını esnetince başladı: 3 ayda -%7.","mudahale","1 ay"),
S("Şanghay Bileşik (Çin)","Balon Zirvesi","endeks","12 Haziran 2015 · Kapanış","Şanghay 1 yılda +%150: marjinli bireysel yatırımcı rekorda",
  ["Şanghay Bileşik 12 ayda +%150 ile 5.100'ü aştı; yeni aracı kurum hesabı haftada milyonlarla açılıyor.",
   "Kredili (marjinli) hisse alımı rekorda; devlet medyası aylar önce '4.000 puan boğa piyasasının sadece başlangıcı' yazdı.",
   "Bugün Çin SPK'sı, aracı kurumların kayıt dışı (gölge) kredili işlemlerine sınırlama getireceğini açıkladı."],
  5121.6,5166.4,-24,"Zirve o gündü: bir haftada -%13, bir ayda -%24, üç ayda -%40 — devletin 'milli takım' alımlarına ve hisselerin yarısının işleme kapatılmasına rağmen. Kredili bireysel yatırımcı rekor kırarken kredi daralırsa, zincirleme zorunlu satış başlar.","kalabalik","1 ay"),
S("Moderna","Biyotek Hype","sok","18 Mayıs 2020 · Kapanış","Moderna aşı verisiyle +%20 uçtu — aynı akşam yeni hisse sattı",
  ["Moderna, aşının ilk 8 gönüllüde nötralize edici antikor ürettiğini açıkladı; hisse tek günde +%20 ile 80$'a çıktı.",
   "Aynı akşam şirket 1,25 milyar $'lık yeni hisse satışı duyurdu — yükselişi sermaye toplamak için kullanıyor.",
   "Veri bir basın bülteniyle geldi; 45 gönüllünün tamamına ait bilimsel detay henüz yok."],
  66.69,80,-10,"Ertesi gün 'veri eksik' eleştirileriyle -%10, bir haftada -%28. Ama hikâye yanlış değildi: Kasım'daki %94,5 etkinlik verisiyle 1 yılda +%99. Kısa vadede 'hype + hisse satışı' düşüşü, uzun vadede temel doğru çıkabilir — vade, kararın yarısıdır.","sat","1 hafta"),
S("Nikkei 225","Balon Zirvesi","endeks","29 Aralık 1989 · Yılın son kapanışı","Nikkei 38.915: Japonya dünyanın en değerli borsası (1989'un son günü)",
  ["Nikkei yılın son günü 38.915 ile tarihî zirvede; Japon borsası dünya borsa değerinin ~%40'ı.",
   "Ortalama F/K 60'ın üstünde; Tokyo'daki imparatorluk sarayının arazisinin Kaliforniya'nın tamamından değerli olduğu konuşuluyor.",
   "Japonya MB'nin yeni başkanı 25 Aralık'ta faizi artırdı; piyasa 'Japonya farklı, düşmez' diyor."],
  38877,38915.9,-40,"O kapanış 34 yıl boyunca aşılamadı: 3 ayda -%27, 1 yılda -%40. Faiz artırımı başlamışken 60 F/K'lık balona 'bu sefer farklı' denmez.","faiz","1 yıl"),
S("Nasdaq Bileşik","Balon Zirvesi","endeks","10 Mart 2000 · Kapanış","Nasdaq 5.000'i aştı: 'yeni ekonomi' coşkusu zirvede",
  ["Nasdaq Bileşik 5.048 ile rekor kapadı: bir yılda iki katından fazla, 1995'ten beri ~5 kat.",
   "Kâr etmeyen internet şirketleri halka arzın ilk günü ikiye katlıyor; 'eski ölçütler yeni ekonomide geçmez' deniyor.",
   "FED 1999'dan beri faiz artırıyor; Mart sonunda yeni artırım bekleniyor."],
  4897.3,5048.6,-17,"Zirve o gündü: bir ayda -%17, bir yılda -%62 (2002'ye kadar -%78). Nasdaq 5.048'i ancak 15 yıl sonra geçebildi.","kalabalik","1 ay"),
S("Netflix","Strateji Hatası","sok","19 Eylül 2011 · Kapanış","Netflix DVD işini 'Qwikster'a ayırıyor: zam üstüne kafa karışıklığı",
  ["Netflix Temmuz'da DVD+dijital paketi ikiye ayırıp fiyatı %60 artırdı; abone kaybı endişesiyle hisse zirvesinden neredeyse yarıya indi.",
   "Pazar gecesi CEO Hastings özür diledi ve DVD işini 'Qwikster' adlı ayrı bir markaya taşıyacağını açıkladı — müşteri iki ayrı site kullanacak.",
   "Bugün hisse -%7,4 kapadı; 'Netflix müşterisini dinlemiyor' eleştirisi yayılıyor."],
  2.217,2.054,-22,"Karmaşa büyüdü: 1 ayda -%22. Qwikster 3 hafta sonra iptal edildi, ama Ekim bilançosunda 800 bin abone kaybı açıklanınca hisse tek günde -%35; 3 ayda -%51. Müşteri güvenini sarsan strateji hatası, geri alınsa bile bilançoya bir çeyrek gecikmeyle yansır.","hik","1 ay"),
S("Tesla","Tweet Şoku","sok","7 Ağustos 2018 · Kapanış","Musk: 'Tesla'yı 420$'dan borsadan çekmeyi düşünüyorum. Fon hazır.'",
  ["Musk borsa saatinde Twitter'dan 'Tesla'yı 420$'dan özele almayı düşünüyorum. Fon hazır.' yazdı; hisse +%11 kapadı.",
   "420$, günün fiyatına ~%20 prim demek; ~70 milyar $'lık bir şirket değeri — finansmanın kaynağı açıklanmadı.",
   "Borsa işlemi kısa süre durdurdu; SEC'e resmî bir bildirim yapılmadı. Short'lar kıstırıldı."],
  22.8,25.3,-26,"Fon hazır değildi: plan 17 gün sonra iptal edildi; SEC dava açtı, Musk yönetim kurulu başkanlığını bıraktı ve 20 milyon $ ceza ödedi. Hisse 1 ayda -%26. Kanıtı olmayan 'kesin' iddiaya fiyat verilmez — tweet'le gelen prim, tweet'le gider.","hik","1 ay"),
S("Ethereum","Balon Zirvesi","kripto","13 Ocak 2018 · Gün sonu","Ethereum 1.400$: ICO çılgınlığı zirvede",
  ["Ethereum bir yılda yüz katından fazla yükseldi: ~10$'dan 1.400$'a; piyasa değeri 130 milyar $'ı aştı.",
   "2017'de ICO'larla (çoğu Ethereum üzerinde token) 6 milyar $'a yakın para toplandı; sadece 'whitepaper' ile milyonlar toplanıyor.",
   "Güney Kore ve Çin'den kripto düzenlemesi haberleri geliyor; 'kurumsal para yakında' söylemi hâkim."],
  1253.9,1388,-38,"Zirve oydu: bir ayda -%38, bir yılda -%92 (Aralık'ta ~84$). ICO'ların topladığı ETH'ler satıldıkça arz baskısı arttı. Talebi kendi balonuna dayanan varlık, balon sönerken iki kat sert düşer.","kalabalik","1 ay"),
S("Bitcoin","Beklenen Olay","kripto","16 Aralık 2017 · Gün sonu","CME'de Bitcoin vadelisi açılıyor: 'kurumsal para geliyor'",
  ["Bitcoin yılbaşından beri ~19 kat: 1.000$'dan 19.000$'a; aile sofralarında konuşuluyor.",
   "İlk Bitcoin vadelisi geçen hafta CBOE'de açıldı; dünyanın en büyük vadeli borsası CME'de yarın açılıyor.",
   "'Wall Street geliyor, 100 bin kapıda' tahminleri yayılıyor; 'Bitcoin nasıl alınır' aramaları rekorda."],
  19102.7,19102.7,-30,"Vadeli işlemler SHORT açmayı da mümkün kıldı: bir haftada -%30, bir yılda -%83. 'Kurumsal ürün geliyor' coşkusunun zirvesi, ürünün açıldığı gündü.","sat","1 hafta"),
S("YPF (Arjantin)","Seçim Şoku","sok","20 Kasım 2023 · Açılış öncesi (NYSE)","Arjantin'de Milei kazandı: petrol devi YPF nasıl açılır?",
  ["Pazar günkü ikinci turda liberter Javier Milei ~%56 ile kazandı; 'devleti küçültme, dolarizasyon, özelleştirme' vaat ediyor.",
   "Milei kampanyada devlet kontrolündeki petrol şirketi YPF'nin yeniden yapılandırılıp özelleştirileceğini söyledi.",
   "Arjantin'de yıllık enflasyon %140'ın üzerinde; Buenos Aires borsası bugün tatil — tepkiyi New York'taki ADR'ler verecek."],
  10.73,15.01,40,"YPF New York'ta +%40 kapattı; 6 ayda +%119, 1 yılda +%231. Rejim değişikliği vaat eden seçimde, devlet müdahalesiyle en çok baskılanmış şirket en sert yeniden fiyatlanır.","donus","1 gün"),
S("USD/RUB (Dolar/Ruble)","Yaptırım Şoku","sok","10 Mart 2022 · Kapanış","Ruble tarihi dipte: 'Rusya iflas eder' manşetleri",
  ["Yaptırımlarla Rusya Merkez Bankası'nın ~300 milyar $'lık rezervi donduruldu, bankalar SWIFT'ten çıkarıldı; ruble iki haftada ~%40 değer kaybetti.",
   "Merkez bankası faizi %9,5'ten %20'ye çıkardı; ihracatçılar döviz gelirinin %80'ini rubleye çevirmek zorunda, yabancıların varlık satması yasak.",
   "Kredi derecelendirme kuruluşları Rusya'yı temerrüt eşiğine indirdi; 'ruble kâğıt parçasına dönecek' manşetleri."],
  109.5,138.71,-43,"Tersine döndü: sermaye kontrolleri ve rekor enerji ihracat gelirleri rubleye talep yarattı; dolar/ruble bir haftada -%27, bir ayda -%43, üç ayda -%56 (ruble 7 yılın en güçlü seviyesinde).","kontrol","1 ay"),
S("FTT (FTX tokenı)","Borsa Çöküşü","kripto","7 Kasım 2022 · Gün sonu","Binance CEO'su 'FTT'lerimizi satıyoruz' dedi: FTX'in tokenı 22$'da",
  ["CoinDesk, FTX'in kardeş şirketi Alameda'nın bilançosunun büyük kısmının FTX'in kendi tokenı FTT'den oluştuğunu yazdı.",
   "Binance CEO'su CZ, elindeki FTT'leri tasfiye edeceğini tweetledi; Alameda CEO'su hepsini 22$'dan almayı teklif etti.",
   "FTX'ten para çekme talepleri artıyor; FTX CEO'su 'FTX iyi durumda, varlıklar yerinde' diyor."],
  22.26,22.08,-75,"Ertesi gün FTX para çekimlerini durdurdu: FTT tek günde -%75, bir haftada -%93; FTX 11 Kasım'da iflas etti. Değeri kendini basan borsanın ayakta kalmasına bağlı token, 'bizimki sağlam' açıklamasıyla değil ancak rezerv kanıtıyla savunulur.","olum","1 gün"),
S("Luckin Coffee","Muhasebe Skandalı","sok","2 Nisan 2020 · Açılış öncesi","Luckin Coffee: 'Satışların bir kısmı uyduruldu' itirafı",
  ["Luckin açılış öncesi, iç soruşturmada COO'nun 2019 satışlarından ~2,2 milyar yuanı (~310 milyon $) uydurduğunun tespit edildiğini açıkladı.",
   "Ocak'ta Muddy Waters'ın paylaştığı anonim raporda aynı iddia vardı; şirket o zaman 'asılsız' demişti.",
   "Hisse dün 26$'dan kapadı; 'uydurma sadece bir kısım, şirket 4.500 şubeyle büyümeye devam ediyor' diyenler var."],
  26.2,6.4,-76,"Günü -%75,6 kapadı; birkaç gün sonra işlem durduruldu, Haziran'da Nasdaq'tan çıkarıldı. Muhasebe hilesinde 'sadece bir kısım' yoktur — bir rakam yalansa, hepsi şüphelidir.","hik","1 gün")
];

/* Niş dersler (mevcut PK_LESSONS'a eklenir) */
Object.assign(window.PK_LESSONS, {
  taahhut:  "<b>Merkez bankası 'asla' dese bile taahhüt bozulabilir.</b> Bir kurun/fiyatın sabit kalacağına güvenen kaldıraçlı pozisyon tek sabahta silinir: sabitlik risk yokluğu değil, birikmiş risktir.",
  niyet:    "<b>İmzalanmamış anlaşma, anlaşma değildir.</b> 'Niyet' ile şişen fiyat, detay (ve soruşturma) gelince çöker; hikâyenin sağlamlığını fiyatın hızına göre değil, belgeye göre ölç.",
  gecikme:  "<b>Kötü haberin ilk günü sakin geçmesi, tehlikenin bittiği anlamına gelmez.</b> Büyük fonların çıkışı günler sürer; ağır iddiaların fiyatlanması ilk manşetten sonra başlar.",
  mudahale: "<b>Kur müdahalesi zaman kazandırır, trendi temel çevirir.</b> Faiz farkı gibi asıl sürücü değişmedikçe müdahale geçici geri çekilme yaratır; dönüş politika değişince gelir.",
  kontrol:  "<b>Sermaye kontrolü, fiyatı piyasanın değil kuralın belirlemesi demektir.</b> Zorunlu döviz bozdurma ve çıkış yasakları varken 'çöküş' manşetiyle pozisyon alınmaz — akışı kim zorunlu kılıyor, ona bak."
});

/* Niş senaryolar için nitel bağlam (make5 ilk 2'sini gösterir) */
Object.assign(window.PK_DETAILS, {
"Dolar/TL 7'yi gördü: rahip krizi ve yaptırım pazartesisi":["🌍 Ortam: ABD ile diplomatik kriz yaptırıma dönüştü; yüksek dış borç ve cari açık kırılganlığı artırıyor.","📊 Varlık: Dolar/TL bir haftada 5,3'ten 7'ye fırladı — kur tarihinin en dikey hareketi.","🗣️ Duyarlılık: Döviz bürolarında kuyruk; 'dolar 10 olur' söylemi sokakta."],
"ECB'nin dev QE'si kapıda: İsviçre MB 1,20 tabanını ne kadar savunabilir?":["🌍 Ortam: Euro bölgesinde deflasyon riski; ECB tarihî bir parasal genişlemeye hazırlanıyor.","📊 Varlık: SNB'nin döviz rezervleri GSYH'nin ~%80'ine ulaştı — tabanı savunmanın bedeli büyüyor.","🗣️ Duyarlılık: Kaldıraçlı 'taban kırılmaz' pozisyonu kalabalık; oynaklık neredeyse sıfır."],
"UBS, Credit Suisse'i hafta sonu zorla devraldı: ilk gün kapanışı":["🌍 Ortam: ABD'de SVB çöküşünün ardından banka güveni sarsıldı; mevduatlar büyük bankalara kaçıyor.","📊 Varlık: UBS, İsviçre'nin tek küresel bankası olarak kalıyor — rakipsiz ama dev bir entegrasyon yüküyle.","🗣️ Duyarlılık: AT1 tahvillerinin silinmesi Avrupa banka tahvillerinde panik yarattı."],
"Kodak iki günde +%1.150: devletten ilaç üretimi kredisi":["🌍 Ortam: Pandemi, ilaç tedarikinde Çin'e bağımlılığı gündeme taşıdı; hükümet 'yerli üretim' teşvik ediyor.","📊 Varlık: Kodak on yıldır küçülen, iflastan dönmüş bir fotoğraf şirketi; piyasa değeri iki günde 10 katına çıktı.","🗣️ Duyarlılık: Bireysel yatırımcı uygulamalarında en çok konuşulan hisse — hype zirvede."],
"Pfizer aşısı %90 etkili: 'kapanan dünyanın' hissesi Carnival":["🌍 Ortam: İkinci dalga ve kapanmalar sürüyor; piyasa pandemi kazananları ile kaybedenleri arasında keskin ayrılmış.","📊 Varlık: Carnival iflası önlemek için yüksek faizle borçlandı ve yeni hisse bastı; kruvaziyerler hâlâ yasaklı.","🗣️ Duyarlılık: 'Aşı en erken 2021 ortası, etkinlik de düşük olur' beklentisi yaygındı."],
"Bitcoin tek günde -%39: 4.800$ — kapitülasyon mu, ölüm mü?":["🌍 Ortam: Küresel dolar sıkışması: fonlar marj çağrıları için satılabilen her varlığı satıyor.","📊 Varlık: Bitcoin'in 2 ay sonra 'halving' (arz yarılanması) yaşayacağı biliniyor.","🗣️ Duyarlılık: Korku endeksi tarihî dipte; kripto forumlarında 'deney bitti' mesajları."],
"Porsche, VW'nin %74'ünü kontrol ettiğini açıkladı: short'lar kıstırıldı":["🌍 Ortam: Lehman sonrası küresel çöküş; otomotiv hisseleri en çok short'lanan sektör.","📊 Varlık: VW adi hissesinin serbest dolaşımı, açık short pozisyonlarının yarısı kadar kaldı.","🗣️ Duyarlılık: Short'lar 'VW'nin temelleri bu fiyatı taşımaz' diyor — ama kapatmak için hisse bulmak zorundalar."],
"Kara Pazartesi'nin ertesi sabahı: S&P tek günde -%20,5":["🌍 Ortam: 1987 boyunca faizler yükseldi, dolar zayıfladı; borsa yılın ilk yarısında +%40 koşmuştu.","📊 Varlık: Endeks iki günde tüm yılın kazancını sildi; değerlemeler bir günde 'ucuz' bölgeye geldi.","🗣️ Duyarlılık: 'Yeni 1929, Büyük Buhran geliyor' manşetleri; aracı kurumlara telefonla ulaşılamıyor."],
"Lehman Brothers iflas başvurusu yaptı: piyasa nasıl açılır?":["🌍 Ortam: Konut balonu patladı; ipotek teminatlı menkul kıymetler bankaların bilançolarını eritiyor.","📊 Varlık: S&P 500 zaten 2007 zirvesinden ~-%20; finans hisseleri çöküşte.","🗣️ Duyarlılık: 'Hükümet büyük bankayı batırmaz' varsayımı ilk kez yıkıldı."],
"Hindenburg raporu: Adani'de ilk gün sadece -%1,5":["🌍 Ortam: Adani Grubu Hindistan'ın altyapı şampiyonu; kurucusu dünyanın en zengin 3. kişisi.","📊 Varlık: Grup şirketleri çok yüksek çarpanlarda ve yüksek borçlu; serbest dolaşımdaki hisse oranı düşük.","🗣️ Duyarlılık: Yerel yatırımcı 'yabancı saldırısı' diyor; yabancı fonlar sessiz."],
"Mini bütçe şoku: sterlin tek günde -%3,6, 'parite' manşetleri":["🌍 Ortam: İngiltere'de enflasyon %10'a yakın; merkez bankası faiz artırırken hükümet mali genişleme yapıyor.","📊 Varlık: Emeklilik fonlarının kaldıraçlı tahvil stratejileri (LDI) teminat çağrısıyla sıkışıyor.","🗣️ Duyarlılık: Piyasa hükümetin mali disiplinine güvenini yitirdi; 'gelişmekte olan ülke gibi fiyatlanıyor' yorumları."],
"Japonya 24 yıl sonra ilk kez yen aldı: dolar/yen döner mi?":["🌍 Ortam: FED yılın en agresif sıkılaştırmasında; Japonya ise getiri eğrisi kontrolüyle faizleri sıfırda tutuyor.","📊 Varlık: Yen yıl başından beri dolara karşı ~%20 değer kaybetti — 24 yılın en zayıf seviyesi.","🗣️ Duyarlılık: Carry trade (ucuz yenle borçlanıp dolar almak) en kalabalık makro pozisyon."],
"Şanghay 1 yılda +%150: marjinli bireysel yatırımcı rekorda":["🌍 Ortam: Çin ekonomisi yavaşlarken hükümet borsayı 'refah kanalı' olarak destekliyor.","📊 Varlık: Borsa yükselişi kâr büyümesinden kopmuş; küçük hisselerde F/K 100'ü aşıyor.","🗣️ Duyarlılık: Çiftçiden öğrenciye herkes hisse konuşuyor — 'devlet düşmesine izin vermez' inancı güçlü."],
"Moderna aşı verisiyle +%20 uçtu — aynı akşam yeni hisse sattı":["🌍 Ortam: Pandemi zirvede; dünyanın ilk aşı verisi bekleniyor, biyoteknoloji hisseleri her haberde uçuyor.","📊 Varlık: Moderna'nın piyasaya çıkmış tek bir ürünü yok; değerlemesi tamamen aşı umuduna dayalı.","🗣️ Duyarlılık: 'Aşı yarışını kazanan şirket' anlatısı haberin detayını gölgeliyor."],
"Nikkei 38.915: Japonya dünyanın en değerli borsası (1989'un son günü)":["🌍 Ortam: Yıllardır süren ucuz kredi, arsa ve hisse fiyatlarını birlikte şişirdi.","📊 Varlık: Japon bankaları dünyanın en büyükleri; şirketler birbirinin hissesini çapraz tutuyor.","🗣️ Duyarlılık: 'Japonya ekonomik süper güç, ABD'yi geçecek' söylemi zirvede."],
"Nasdaq 5.000'i aştı: 'yeni ekonomi' coşkusu zirvede":["🌍 Ortam: İnternet devrimi gerçek; ama sermaye kâr etmeyen şirketlere sınırsız akıyor.","📊 Varlık: Nasdaq 100'ün F/K'sı 100'ün üzerinde; birçok şirketin nakdi 1-2 yılda bitecek.","🗣️ Duyarlılık: Televizyonda hisse programları reyting rekoru kırıyor; 'değer yatırımı öldü' deniyor."],
"Netflix DVD işini 'Qwikster'a ayırıyor: zam üstüne kafa karışıklığı":["🌍 Ortam: Dijital yayına geçiş hızlanıyor; içerik lisans maliyetleri sert artıyor.","📊 Varlık: Netflix'in gelirinin büyük kısmı hâlâ DVD işinden; dijitale geçiş bedelini müşteriye yansıtıyor.","🗣️ Duyarlılık: Sosyal medyada abonelik iptal kampanyaları; marka güveni ilk kez sarsıldı."],
"Musk: 'Tesla'yı 420$'dan borsadan çekmeyi düşünüyorum. Fon hazır.'":["🌍 Ortam: Tesla Model 3 üretim sorunlarıyla boğuşuyor; nakit yakımı yüksek.","📊 Varlık: Tesla en çok short'lanan büyük ABD hisselerinden; Musk short'çularla açıkça kavgalı.","🗣️ Duyarlılık: '420' sayısının bir şaka olup olmadığı tartışılıyor."],
"Ethereum 1.400$: ICO çılgınlığı zirvede":["🌍 Ortam: 2017'de kripto piyasa değeri ~30 kat büyüdü; düzenleme neredeyse yok.","📊 Varlık: ETH talebinin büyük kısmı, ICO'lara katılmak için alınan tokenlardan geliyor.","🗣️ Duyarlılık: 'Ethereum Bitcoin'i geçecek (flippening)' tartışması zirvede."],
"CME'de Bitcoin vadelisi açılıyor: 'kurumsal para geliyor'":["🌍 Ortam: Kripto borsaları yeni kullanıcı kaydını durduracak kadar yoğun; işlem ücretleri rekorda.","📊 Varlık: Bitcoin 3 ayda ~5 kat; Aralık'ın ilk yarısında 10 binden 19 bine çıktı.","🗣️ Duyarlılık: Taksi şoförleri, aile sofraları, akşam haberleri — herkes Bitcoin konuşuyor."],
"Arjantin'de Milei kazandı: petrol devi YPF nasıl açılır?":["🌍 Ortam: Arjantin on yıllardır tekrarlayan kur krizleri ve borç temerrütleriyle boğuşuyor.","📊 Varlık: YPF dünyanın en büyük kaya petrolü sahalarından Vaca Muerta'yı işletiyor; fiyat kontrolleri kârını baskılıyor.","🗣️ Duyarlılık: Uluslararası fonlar Arjantin'e yıllardır küs; pozisyonlar çok hafif."],
"Ruble tarihi dipte: 'Rusya iflas eder' manşetleri":["🌍 Ortam: Batı'nın en kapsamlı yaptırım paketi; Rus borsası haftalardır kapalı.","📊 Varlık: Rusya'nın petrol-gaz ihracatı sürüyor ve enerji fiyatları rekor bölgede — döviz girişi devam ediyor.","🗣️ Duyarlılık: Yabancı yatırımcılar Rusya'dan çıkamıyor; 'ruble ticarete kapanır' bekleniyor."],
"Binance CEO'su 'FTT'lerimizi satıyoruz' dedi: FTX'in tokenı 22$'da":["🌍 Ortam: 2022 kripto kışı: LUNA ve Celsius çöktü, güven zaten kırılgan.","📊 Varlık: FTT'nin değeri FTX'in işlem gelirine ve sürekliliğine bağlı; en büyük sahiplerinden biri kardeş şirket Alameda.","🗣️ Duyarlılık: FTX, 'kriz kurtarıcısı' imajına sahipti — sektörün en güvenilir borsası sayılıyordu."],
"Luckin Coffee: 'Satışların bir kısmı uyduruldu' itirafı":["🌍 Ortam: Pandemi nedeniyle Çin'de şubelerin çoğu kapalı; ABD'de Çin şirketlerinin denetimi tartışmalı.","📊 Varlık: Luckin agresif indirimlerle büyüdü, hiç kâr etmedi; büyüme hikâyesi satış rakamlarına dayanıyordu.","🗣️ Duyarlılık: Kurumsal yatırımcılar Ocak'taki raporu 'kanıtsız' bulup hisseyi tutmayı sürdürmüştü."]
});
